# ~/.config/starship.toml

[character]
success_symbol = "[;](bold green)"
error_symbol = "[;](bold red)"

[gcloud]
disabled = true

[git_status]
stashed = ""
style = "bright-cyan"
modified = "[!($count)](yellow)"
untracked = "[?($count)](bright-blue)"
ahead = "[⇡($count)](cyan)"
behind = "[⇣($count)](dark-cyan)"
# untracked = ""

[git_branch]
style = "green"

[git_commit]
disabled = false
commit_hash_length = 7    # how many chars of the hash to show (default 7)
only_detached = false     # if true, only shows hash when in detached HEAD state
tag_disabled = true       # hides the tag name even if HEAD is on a tag
style = "bold green"

[directory]
style = "bold white"
truncation_length = 3
truncate_to_repo = true
